# Generated by Django 4.2.28 on 2026-02-24 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('ADMIN', 'Admin')], default='ANALYST', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('can_demask', models.BooleanField(default=False)),
                ('demask_threshold', models.FloatField(default=0.8, help_text='Minimum risk score to demask data')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('account_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('sender_account', models.CharField(max_length=50)),
                ('receiver_account', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('risk_score', models.FloatField()),
                ('xgb_score', models.FloatField()),
                ('gnn_score', models.FloatField()),
                ('network_factor', models.FloatField(default=1.0)),
                ('risk_category', models.CharField(max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['risk_score'], name='dashboard_t_risk_sc_6cf27b_idx'), models.Index(fields=['transaction_id'], name='dashboard_t_transac_c32ad0_idx'), models.Index(fields=['timestamp'], name='dashboard_t_timesta_00a43b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_role', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('VIEW', 'View Transaction'), ('DEMASK', 'De-mask Sensitive Data'), ('EXPORT', 'Export Data'), ('BATCH_UPLOAD', 'Batch Upload'), ('SINGLE_ANALYZE', 'Single Transaction Analysis'), ('PERMISSION_DENIED', 'Permission Denied')], max_length=50)),
                ('description', models.TextField()),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('data_masked', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='dashboard_a_user_id_a6b235_idx'), models.Index(fields=['action', 'timestamp'], name='dashboard_a_action_abda66_idx'), models.Index(fields=['transaction_id'], name='dashboard_a_transac_dc6f8f_idx')],
            },
        ),
    ]
