# Generated by Django 5.2.8 on 2026-02-28 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('report_type', models.CharField(default='NATIONAL_SECURITY_DOSSIER', max_length=50)),
                ('officer_name', models.CharField(max_length=200)),
                ('officer_role', models.CharField(max_length=50)),
                ('officer_employee_id', models.CharField(blank=True, max_length=50)),
                ('evidence_timestamp', models.DateTimeField()),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_transactions_analyzed', models.IntegerField()),
                ('total_volume_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('critical_risk_count', models.IntegerField()),
                ('typologies_detected', models.JSONField(default=list)),
                ('model_used', models.CharField(default='gemma3:4b', max_length=50)),
                ('entity_anonymization_applied', models.BooleanField(default=True)),
                ('risk_narrative', models.TextField()),
                ('network_summary', models.JSONField()),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_generation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('pdf_file_hash', models.CharField(blank=True, max_length=64)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified by Officer'), ('SUBMITTED', 'Submitted to FRC'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('cbk_reporting_required', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forensic_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generation_timestamp'],
                'indexes': [models.Index(fields=['case_id'], name='dashboard_f_case_id_984be0_idx'), models.Index(fields=['generated_by', 'generation_timestamp'], name='dashboard_f_generat_616e7c_idx'), models.Index(fields=['verification_status'], name='dashboard_f_verific_2e1e52_idx')],
            },
        ),
    ]
