# Generated by Django 5.2.8 on 2026-03-02 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_forensicreportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_account', models.CharField(help_text='Account ID under investigation', max_length=100)),
                ('gemma_summary', models.TextField(help_text='AI-generated forensic analysis text')),
                ('risk_score', models.FloatField(help_text='Numerical risk score from GNN/Isolation Forest')),
                ('case_reference', models.CharField(blank=True, help_text='Optional case reference number', max_length=50)),
                ('transaction_count', models.IntegerField(default=0, help_text='Number of transactions analyzed')),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0, help_text='Total transaction volume', max_digits=20)),
                ('typologies_identified', models.JSONField(default=list, help_text='List of AML typologies detected')),
                ('network_connections', models.IntegerField(default=0, help_text='Number of connected entities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_generated', models.BooleanField(default=False)),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('report_download_count', models.IntegerField(default=0)),
                ('investigation_status', models.CharField(choices=[('ONGOING', 'Ongoing Investigation'), ('COMPLETED', 'Investigation Completed'), ('ESCALATED', 'Escalated to FRC'), ('CLOSED', 'Case Closed')], default='ONGOING', max_length=20)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['officer', '-created_at'], name='dashboard_a_officer_3c53d4_idx'), models.Index(fields=['target_account'], name='dashboard_a_target__5a914a_idx'), models.Index(fields=['investigation_status'], name='dashboard_a_investi_7626fb_idx'), models.Index(fields=['created_at'], name='dashboard_a_created_079b26_idx')],
            },
        ),
    ]
